# Generated by Django 5.2.8 on 2025-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
