# Generated by Django 5.2.8 on 2025-11-08 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_weatherrecord_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_records_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_records_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
